version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - checkout
      - run:
          name: Syntax check
          command: perl -c bwftool.pl

